CREATE OR REPLACE EDITIONABLE PROCEDURE HELLO_WORLD AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello World');
    --Test3

    --TEST2
    --UPDATED_BY_DEV1
    --UPDATED_BY_DEV1 - 2026.04.24
    --UPDATED_BY_DEV2 - 2026.04.24 Change on Second user
END;
/

