CREATE OR REPLACE EDITIONABLE PROCEDURE HELLO_WORLD AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello World');
    --Test3223

    --Test4
    --TEST2
    --UPDATED_BY_DEV1 ---2 -- Line 8 15:05

    --UPDATED_BY_DEV2 - 2026.04.24 Change on Second user
END;
/

